name = "InverseLangevinApproximations"
uuid = "b82787f2-62be-403e-9078-6d9feafd7ee3"
authors = ["Carson Farmer <59753859+cfarm6@users.noreply.github.com> and contributors"]
version = "0.1.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
DocStringExtensions = "0.9"
julia = "1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "InteractiveUtils"]
